# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ee37dbcf7c79d5693333a4e3602b878e763b39c308716663ab7c7808a0df8666c8bec2270b6480a5d4eb733c66b2945f57a561ec68005ba821bdfe3d027070

test:
  secret_key_base: 96d1831ff114a96c44149515d7c78f8eb944ecf35caea281e26c322350650c4244d29f2581d48223c4234dafd73009a97925d48785a9bedf1dcacc96d5a55612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
